# Generated by Django 4.1.6 on 2023-02-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_categories_name_categories_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo_url',
            field=models.URLField(max_length=500),
        ),
    ]
