# Generated by Django 4.1.6 on 2023-02-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_date_bid_listing_bid_value_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
