# Generated by Django 4.1.6 on 2023-02-25 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
