# Generated by Django 4.1.6 on 2023-02-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winners',
            new_name='Winner',
        ),
    ]
